### ISSUE TITLE
슬랙 pull request 연동 문의

### ISSUE THREAD

**Issue by amorfati0310** [kiljh-me/codesquad-blog-collection#1]
@kiljh-me 님 슬랙 채널에 `github subscribe /kiljh-me/codesquad-blog-collection` 연동 시켜주실 수 있나요
개인 repo라 아마 개인 계정으로 연동 할 수 있는 것 같아유 ㅎㅅㅎ

**Comment by kiljh-me** [comment]
연동해봤습니다.

**Comment by kiljh-me** [comment]
최대 한도가 넘었다고 안되네요~
